FROM ubuntu:18.04
WORKDIR /usr/src/app
COPY . .
RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && useradd -m user && \
    apt-get install -y nodejs && \
    npm ci --no-optional && npm run build && npm install -g serve && \
    apt-get purge -y --auto-remove curl && rm -rf /var/lib/apt/lists/
EXPOSE 5000
USER user
CMD ["serve", "-s", "-l", "5000", "build"]