version: '3.8'

services:
  back-end:
    image: example-backend
    build: ./example-backend
    ports:
      - 8080:8080
  front-end:
    image: example-frontend
    build: ./example-frontend
    ports:
      - 5000:5000