version: '3.8'

services:
  front-end:
    image: example-frontend
    build: ./example-frontend
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL= http://localhost:8080/

  back-end:
      build: ./example-backend
      command: ./server
      image: "example-backend"
      container_name: test_run
      restart: unless-stopped
      expose:
        - 8080
      ports:
        - 8080:8080
      depends_on:
        - redis-server
      environment:
        - REDIS_HOST=redis-server

  redis-server:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
