FROM node:16-alpine as build
WORKDIR /usr/src/app
COPY . .
RUN npm ci --no-optional && npm run build && \
    adduser -D user
USER user

FROM node:16-alpine
WORKDIR /usr/src/app
COPY package*.json .
RUN npm install --only=production && npm install -g serve 
COPY --from=0 /usr/src/app/build ./build
EXPOSE 5000
CMD ["serve", "-s", "-l", "5000", "build"]